name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Docker Compose # שלב חדש שנוסף
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-todo-app:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/flask-todo-app:latest

      - name: Run Docker Compose
        run: docker-compose up --build -d

      - name: Wait for services
        run: |
          sleep 10

      - name: Run Tests
        run: docker-compose exec -T web pytest
      - name: Stop Docker Compose services
        if: always()
        run: docker-compose down

      - name: Update CD Repository (GitOps)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://Gilad88:${{ secrets.GH_PAT_CD_REPO }}@github.com/Gilad88/flask-todo-infrastructure.git cd_repo_path
          cd cd_repo_path
          # בדיקה האם sed זמין (לדיבוג)
          which sed
          # פקודת sed מתוקנת: מחפשת את השורה המלאה ומחליפה את התגית
          sed -i "s|image: gilad88/flask-todo-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/flask-todo-app:${{ github.sha }}|" kubernetes/deployment.yaml
          git add kubernetes/deployment.yaml
          git commit -m "Update Flask To-Do App image to ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
        env:
          GH_PAT_CD_REPO: ${{ secrets.GH_PAT_CD_REPO }}
